/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_jose_21941105;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author josec
 */
public class Carrera extends javax.swing.JFrame {

    Color color;
    boolean selectTabla;
    boolean selectComenzar;
    boolean ganador;
    RandomAccessFile carros;
    String winner;
    public Carrera() {
        selectTabla=false;
        ganador=false;
        try{
            carros=new RandomAccessFile("carros.jc","rw");
            initComponents();
            this.setVisible(true);
            this.setLocationRelativeTo(null);
            llenarComboBox();
        }catch(IOException e){
            Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE,null,e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Comenzar = new javax.swing.JButton();
        btn_Pausar = new javax.swing.JButton();
        jp_recorrido = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        cb_corredores = new javax.swing.JComboBox<>();
        btn_agregarCorredor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tb_numero = new javax.swing.JTextField();
        tb_corredor = new javax.swing.JTextField();
        btn_color = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tb_pista = new javax.swing.JTextField();
        tb_largo = new javax.swing.JTextField();
        btn_pista = new javax.swing.JButton();
        btn_reiniciar = new javax.swing.JButton();
        cb_tipo = new javax.swing.JComboBox<>();
        jl_pista = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jl_largo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Comenzar.setText("Comenzar");
        btn_Comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, -1, -1));

        btn_Pausar.setText("Pausar");
        getContentPane().add(btn_Pausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 11, -1, -1));
        getContentPane().add(jp_recorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, 612, 66));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Corredor", "Distancia"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 131, 612, 117));

        getContentPane().add(cb_corredores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 20));

        btn_agregarCorredor.setText("Agregar");
        btn_agregarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarCorredorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarCorredor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, 20));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Numero Identificador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Nombre Corredor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 120, -1));
        getContentPane().add(tb_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 120, -1));
        getContentPane().add(tb_corredor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 120, -1));

        btn_color.setText("Color");
        btn_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 90, -1));

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 90, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Nombre Pista");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Largo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 40, -1));
        getContentPane().add(tb_pista, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 120, -1));
        getContentPane().add(tb_largo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 120, -1));

        btn_pista.setText("Usar Pista");
        btn_pista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pistaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pista, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 130, -1));

        btn_reiniciar.setText("Reiniciar");
        btn_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 130, -1));

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "McQueen", "Convertible", "Nascar" }));
        getContentPane().add(cb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, -1));

        jl_pista.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(jl_pista, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, 20));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 50, 10));

        jl_largo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(jl_largo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 80, 20));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 50, 10));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Pista:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Largo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try{
            int numId = Integer.parseInt(tb_numero.getText());
            long distancia=0;
            String nombre=tb_corredor.getText();
            String tipo =String.valueOf(cb_tipo.getSelectedItem());
            int RGB=color.getRGB();
            int Vmin = (tipo.equals("McQueen")?30:((tipo.equals("Convertible"))?20:40));
            int Vmax = (tipo.equals("McQueen")?30:((tipo.equals("Convertible"))?20:40));
            
            
            if(numeroU(numId)){
                carros.writeInt(numId);
                carros.writeLong(distancia);
                carros.writeUTF(nombre);
                carros.writeInt(RGB);
                carros.writeInt(Vmin);
                carros.writeInt(Vmax);
                carros.writeUTF(tipo);
                JOptionPane.showMessageDialog(null,"***CUCHAO, EL AUTO A SIDO CREADO EXITOSAMENTE***");
                llenarComboBox();
            }else{
                JOptionPane.showMessageDialog(null,"!!!ESTE IDENTIFICADOR YA EXISTE!!!");
            }
            
        } catch (IOException e){
            Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colorActionPerformed
        // TODO add your handling code here:
        JColorChooser colorChooser = new JColorChooser();
        color = JColorChooser.showDialog(this, "Elige un color", Color.white);
        btn_color.setBackground(color);
    }//GEN-LAST:event_btn_colorActionPerformed

    private void btn_pistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pistaActionPerformed
        // TODO add your handling code here:
        String pista = tb_pista.getText();
        long largo=Long.parseLong(tb_largo.getText());
        if(largo>0){
            jl_pista.setText(pista);
            jl_largo.setText(tb_largo.getText());
        }else{
            JOptionPane.showMessageDialog(null,"!!!El largo tiene que ser mayor a 0!!!");
        }
    }//GEN-LAST:event_btn_pistaActionPerformed

    private void btn_agregarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarCorredorActionPerformed
        // TODO add your handling code here:
        try{
            addCarro();
        }catch(IOException e){
            Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_agregarCorredorActionPerformed

    private void btn_ComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComenzarActionPerformed
        // TODO add your handling code here:
        hilo begin=new hilo();
        begin.start();
        selectComenzar=true;
       
    }//GEN-LAST:event_btn_ComenzarActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        
        if(selectComenzar){
            try{
                selectCar();
            }catch(IOException e){
                Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE,null,e);
            }
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void btn_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reiniciarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dfl=(DefaultTableModel)jTable.getModel();
        dfl.setRowCount(0);
        jp_recorrido.setValue(0);
    }//GEN-LAST:event_btn_reiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Comenzar;
    private javax.swing.JButton btn_Pausar;
    private javax.swing.JButton btn_agregarCorredor;
    private javax.swing.JButton btn_color;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_pista;
    private javax.swing.JButton btn_reiniciar;
    private javax.swing.JComboBox<String> cb_corredores;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jl_largo;
    private javax.swing.JLabel jl_pista;
    private javax.swing.JProgressBar jp_recorrido;
    private javax.swing.JTextField tb_corredor;
    private javax.swing.JTextField tb_largo;
    private javax.swing.JTextField tb_numero;
    private javax.swing.JTextField tb_pista;
    // End of variables declaration//GEN-END:variables

    public boolean numeroU(int numero)throws IOException{
        carros.seek(0);
        while(carros.getFilePointer()<carros.length()){
            if(carros.readInt()==numero){
                return false;
            }else{
                carros.skipBytes(8);
                carros.readUTF();
                carros.skipBytes(12);
                carros.readUTF();
            }
        }
        return true;
    }
    public void llenarComboBox() throws IOException{
        cb_corredores.removeAllItems();
        carros.seek(0);
        while(carros.getFilePointer()<carros.length()){
            cb_corredores.addItem(String.valueOf(carros.readInt()));
            carros.readLong();
            carros.readUTF();
            carros.skipBytes(12);
            carros.readUTF();
        }
    }
    public void addCarro()throws IOException{
        DefaultTableModel model=(DefaultTableModel)jTable.getModel();
        int numero=Integer.parseInt(String.valueOf(cb_corredores.getSelectedItem()));
        numeroU(numero);
        long distancia=carros.readLong();
        String corredor=carros.readUTF();
        if(!CarroTable(String.valueOf(cb_corredores.getSelectedItem()))){
            Object[]x ={numero,corredor,distancia};
            model.addRow(x);
        }else{
            JOptionPane.showMessageDialog(null, "Este Carro ya se encuentra compitiendo");
        }
    }
    public void Distancia(String numero)throws IOException{
        numeroU(Integer.parseInt(numero));
        Random r=new Random();
        carros.skipBytes(8);
        String nombre=carros.readUTF();
        carros.skipBytes(4);
        int min = carros.readInt();
        int max = carros.readInt();
        int distanciaActual = r.nextInt(max-min) + max;
        int lista =CarList(numero);
        int distanciaAnterior=Integer.parseInt(String.valueOf(jTable.getValueAt(lista,2)));
        int distanciaTotal=distanciaActual+distanciaAnterior;
        //jTable.setValueAt(distanciaTotal,lista,2);
        if(distanciaTotal>Integer.parseInt(jl_largo.getText())){
            ganador=true;
            winner=nombre;
        }
        jTable.setValueAt(distanciaTotal,lista,2);
        
    }
    public boolean CarroTable(String numero){
        int filas=jTable.getRowCount();
        System.out.println(filas);
        for(int i=0;i<filas;i++){
            System.out.println(jTable.getValueAt(i, 0));
            if(jTable.getValueAt(i, 0)==numero){
                return true;
            }
        }
        return false;
    }
    
    public int CarList(String numero){
        for(int i=0;i<jTable.getRowCount();i++){
            if(String.valueOf(jTable.getValueAt(i,0)).equals(numero)){
                return i;
            }
        }
        return -1;
    }
   
    
    public void selectCar()throws IOException{
        int lista=Integer.parseInt(String.valueOf(jTable.getSelectedRow()));
        if(lista!=-1){
        int numero=Integer.parseInt(String.valueOf(jTable.getValueAt(lista,0)));
        int distancia=Integer.parseInt(String.valueOf(jTable.getValueAt(lista,0)));
        numeroU(numero);
        carros.skipBytes(8);
        carros.readUTF();
        int color=carros.readInt();
        jp_recorrido.setStringPainted(true);
        jp_recorrido.repaint();
        jp_recorrido.setBackground(new Color(color));
        jp_recorrido.setVisible(true);
        jp_recorrido.setValue(distancia);
        
           
        }
    }
    class hilo extends Thread{
        
        public void run(){
            try{
            while(!ganador){
                for(int i=0;i<jTable.getRowCount();i++){
                    
                    String numero=String.valueOf(jTable.getValueAt(i,0));
                    Distancia(numero);
                    selectCar();
                }
                   
                        
                        try{
                            Thread.sleep(1000);
                        }catch(InterruptedException e){
                            e.printStackTrace();
                        }
                    
                    
                }
            JOptionPane.showMessageDialog(null, winner+" gano");
            
            
            }catch(IOException e){
                Logger.getLogger(Carrera.class.getName()).log(Level.SEVERE,null,e);

            }
        }
        
     
    }
}
